# Form implementation generated from reading ui file 'c:\Users\trits\Desktop\.git\compiler\New_folder\IntermidiateWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(959, 645)
        MainWindow.setStyleSheet("QWidget{\n"
"background-color:rgb(33,33,33);\n"
"color:#FFFFFF;\n"
"}\n"
"QTextEdit{\n"
"background-color:rgb(46,46,46);\n"
"border:0;\n"
"}\n"
"QMenuBar::item:selected{\n"
"color:#000000;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(480, 0, 131, 20))
        font = QtGui.QFont()
        font.setBold(True)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit.setEnabled(True)
        self.textEdit.setGeometry(QtCore.QRect(40, 31, 1041, 671))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 31, 31, 671))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 710, 75, 24))
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 959, 22))
        self.menubar.setObjectName("menubar")
        self.menuDebugging = QtWidgets.QMenu(parent=self.menubar)
        self.menuDebugging.setObjectName("menuDebugging")
        self.menuMap = QtWidgets.QMenu(parent=self.menubar)
        self.menuMap.setObjectName("menuMap")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionStart = QtGui.QAction(parent=MainWindow)
        self.actionStart.setObjectName("actionStart")
        self.actionStop = QtGui.QAction(parent=MainWindow)
        self.actionStop.setObjectName("actionStop")
        self.actionControl_Flow_Graph = QtGui.QAction(parent=MainWindow)
        self.actionControl_Flow_Graph.setObjectName("actionControl_Flow_Graph")
        self.actionSource_Code_Mapping = QtGui.QAction(parent=MainWindow)
        self.actionSource_Code_Mapping.setObjectName("actionSource_Code_Mapping")
        self.menuDebugging.addAction(self.actionStart)
        self.menuMap.addAction(self.actionControl_Flow_Graph)
        self.menuMap.addAction(self.actionSource_Code_Mapping)
        self.menubar.addAction(self.menuDebugging.menuAction())
        self.menubar.addAction(self.menuMap.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "  Intermidiate Code"))
        self.pushButton.setText(_translate("MainWindow", "Run"))
        self.menuDebugging.setTitle(_translate("MainWindow", "Debugging"))
        self.menuMap.setTitle(_translate("MainWindow", "Map"))
        self.actionStart.setText(_translate("MainWindow", "Start"))
        self.actionStop.setText(_translate("MainWindow", "Stop"))
        self.actionControl_Flow_Graph.setText(_translate("MainWindow", "Control Flow Graph"))
        self.actionSource_Code_Mapping.setText(_translate("MainWindow", "Source Code Mapping"))
